Pig Stack Trace
---------------
ERROR 6000: 
<file ankit.pig, line 17, column 0> Output Location Validation Failed for: 'file:///home/ankitkap/dic/hw3/experiments/xxx More info to follow:
Output directory file:/home/ankitkap/dic/hw3/experiments/xxx already exists

org.apache.pig.impl.plan.VisitorException: ERROR 6000: 
<file ankit.pig, line 17, column 0> Output Location Validation Failed for: 'file:///home/ankitkap/dic/hw3/experiments/xxx More info to follow:
Output directory file:/home/ankitkap/dic/hw3/experiments/xxx already exists
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:95)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator.validate(InputOutputFileValidator.java:45)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:303)
	at org.apache.pig.PigServer.compilePp(PigServer.java:1380)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1305)
	at org.apache.pig.PigServer.execute(PigServer.java:1297)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:375)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:353)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:140)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:202)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:173)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:84)
	at org.apache.pig.Main.run(Main.java:607)
	at org.apache.pig.Main.main(Main.java:156)
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory file:/home/ankitkap/dic/hw3/experiments/xxx already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:134)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:80)
	... 26 more
================================================================================
